CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY,
	Username VARCHAR(30) NOT NULL Unique,
	Password VARCHAR(50) NOT NULL,
	Name VARCHAR(50),
	Birthdate DATETIME,
	Age INT,
	Email VARCHAR(50) NOT NULL,
	CONSTRAINT CH_Age CHECK (Age > 14 AND Age <= 110)
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY IDENTITY ,
	FirstName VARCHAR(25),
	LastName VARCHAR(25),
	Birthdate DATETIME,
	Age INT,
	DepartmentId INT FOREIGN KEY REFERENCES Departments (Id),

	CONSTRAINT CH_Age_Employee CHECK (Age >=18 AND Age <= 110)
)

CREATE TABLE Categories (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments (Id) NOT NULL,
)

CREATE TABLE [Status] (
	Id INT PRIMARY KEY IDENTITY,
	[Label] VARCHAR(30) NOT NULL
)

CREATE TABLE Reports (
	Id INT PRIMARY KEY IDENTITY,
	CategoryId INT FOREIGN KEY REFERENCES Categories (Id) NOT NULL,
	StatusId INT FOREIGN KEY REFERENCES [Status] (Id) NOT NULL,
	OpenDate DATETIME NOT NULL,
	CloseDate DATETIME NOT NULL,
	Description VARCHAR(200) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users (Id),
	EmployeeId INT FOREIGN KEY REFERENCES Employees (Id)
)	