CREATE TABLE Towns (
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	[Name] NVARCHAR (30) NOT NULL
)

CREATE TABLE Addresses (
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	AddressText NVARCHAR (50),
	TownId INT NOT NULL FOREIGN KEY REFERENCES Towns (Id)
)

CREATE TABLE Departments (
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	[Name] NVARCHAR (30) NOT NULL
)

CREATE TABLE Employees (
	Id INT PRIMARY KEY NOT NULL IDENTITY,
	FirstName NVARCHAR (30) NOT NULL,
	MiddleName NVARCHAR (30),
	LastName NVARCHAR (30) NOT NULL,
	JobTitle NVARCHAR (15) NOT NULL,
	DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments (Id),
	HireDate DATE NOT NULL,
	Salary DECIMAL (3, 2) NOT NULL,
	AddressId INT NOT NULL FOREIGN KEY REFERENCES Addresses (Id)
)